version: 2
jobs:
    build:
        docker:
          - image: circleci/golang:1
        steps:
            - checkout
            - run: go get -v -t -d ./...
            - run: touch .env
            - run: make
workflows:
    version: 2
    lint_and_test:
        jobs:
            - build

